# Generated by Django 3.2 on 2022-04-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
